seguros/compania/urls.py
from django.conf.urls import url
import compania.views as views

urlpatterns = [
    url(r'^$', views.Home.as_view(), name="compania-home"),
    url(r'^all/$', views.CompaniaList.as_view(), name='compania-list'),
    url(r'^add/$', views.CompaniaCreate.as_view(), name='compania-create'),
    url(r'^add/all/$', views.add_all_companies, name='compania-add-all'),
    url(r'^(?P<pk>\d+)/update/$', views.CompaniaUpdate.as_view(),
        name="compania-update"),
    url(r'^(?P<pk>\d+)/$', views.CompaniaDetail.as_view(),
        name="compania-detail"),
]

seguros/seguros/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from compania import urls as companias_urls
from trabajo import urls as trabajos_urls
# from i18n import urls as i18n_urls
from productor import urls as productores_urls

admin.autodiscover()
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^companias/', include(companias_urls)),
    url(r'^trabajos/', include(trabajos_urls)),
    url(r'^productores/', include(productores_urls)),
    # url(r'^i18n/', include(i18n_urls)),
    url(r'^select2/', include('django_select2.urls')),
]

seguros/compania/models.py
import json
from django.urls import reverse_lazy
from django.db import models


class Compania(models.Model):
    codigo = models.IntegerField()
    portal_web = models.URLField(blank=True, null=True)
    portal_web_alternativo = models.URLField(blank=True, null=True)
    es_descargable = models.BooleanField(default=False)
    descarga_automatizada = models.BooleanField(default=False)
    instructivo_descarga = models.TextField(blank=True)
    instructivo_recupero = models.TextField(blank=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.get_nombre()

    class Meta:
        ordering = ['codigo']

    def get_absolute_url(self):
        return reverse_lazy('compania-detail', kwargs={'pk': self.pk})

    def get_nombre(self):
        try:
            with open('compania/companies.json') as f:
                data = json.load(f)
            nombre = data[str(self.codigo)]['nombre']
        except (KeyError, FileNotFoundError):
            nombre = ''
        return nombre

    def get_nombre_corto(self):
        try:
            with open('compania/companies.json') as f:
                data = json.load(f)
            nombre_corto = data[str(self.codigo)]['nombre_corto']
        except (KeyError, FileNotFoundError):
            nombre_corto = ''
        return nombre_corto

seguros/compania/forms.py
from django import forms
from . import models


class CompaniaUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Compania
        fields = '__all__'
        widgets = {'instructivo_descarga': forms.Textarea(
            attrs={'class': 'materialize-textarea'}),
            'instructivo_recupero': forms.Textarea(
                attrs={'class': 'materialize-textarea'})
        }

seguros/compania/views.py
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from .models import Compania
from .forms import CompaniaUpdateForm


@method_decorator(login_required, 'dispatch')
class Home(ListView):
    model = Compania
    template_name = 'compania_home.html'
    paginate_by = 10


@method_decorator(login_required, 'dispatch')
class CompaniaUpdate(UpdateView):
    model = Compania
    form_class = CompaniaUpdateForm
    success_url = reverse_lazy('compania-list')
    template_name = 'compania_update.html'


@method_decorator(login_required, 'dispatch')
class CompaniaList(ListView):
    model = Compania
    template_name = 'compania_list.html'


@method_decorator(login_required, 'dispatch')
class CompaniaCreate(CreateView):
    model = Compania
    form_class = CompaniaUpdateForm
    template_name = 'compania_update.html'
    success_url = reverse_lazy('compania-list')


@method_decorator(login_required, 'dispatch')
class CompaniaDetail(DetailView):
    model = Compania
    template_name = 'compania_detail.html'


@method_decorator(login_required, 'dispatch')
class CompaniaDelete(DeleteView):
    model = Compania
    template_name = 'compania_confirm_delete.html'
    success_url = reverse_lazy('compania-list')


@login_required
def add_all_companies(request):
    return redirect('compania-home')

seguros/templates/compania/compania_add.html
{% extends 'base.html' %}
{% load static %}
{% block extracss %}
    <link rel="stylesheet" href="{% static 'css/select2-materialize.css' %}">
{% endblock %}
{% block content %}
<div class="row">
  <div class="col s12 m6 offset-m3">
    <div class="card">
      <form action="" method="post"> {% csrf_token %}
        <div class="card-content">
          <span class="card-title">Seleccione la compañía a agregar:</span>
          <div class="input-field">
            {{ form.compania }}
            <label for="id_compania">Compañía</label>
          </div>
        </div>
        <div class="card-action center">
          <button type="submit" class="btn">Aceptar</button>
          <a href="{% url 'productor-detail' prod_id %}" class="btn red darken-1">Cancelar</a>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}
{% block extrajs %}
    <script src="{% static 'js/select2.min.js' %}"></script>
<script charset="utf-8">
  $(document).ready(function() {
/*$('select').formSelect();*/
$('select').select2();
})
</script>
{% endblock %}

seguros/templates/compania/compania_home.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <ul class="collection">
    {% for cia in object_list %}
    <li class="collection-item avatar">
      <a href="{% url 'compania-update' cia.pk %}" class="black-text"><h5>{{ cia|upper }}</h5></a>
      <blockquote>
        <p><a href="#">Portal 1</a> | <a href="#">Portal 2</a></p>
      </blockquote>
    </li>
    {% empty %}
    <a class="btn" href="{% url 'compania-create' %}">Agregar una compañía</a>
    <a class="btn" href="{% url 'compania-add-all' %}">Agregar todas las compañías</a>
    <h4>No se encontraron compañías</h4>
    {% endfor %}
  </ul> 
  {% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="waves-effect">
      <a href="/companias?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
    </li>
    {% endif %}
    <li class="active"><a href="#">{{ page_obj.number }}</a></li>
    {% if page_obj.has_next %}
    <li class="waves-effect">
      <a href="/companias?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
    </li>
    {% endif %}
  </ul>
  {% endif %}
</div>
{% endblock %}

seguros/templates/compania/compania_password_create.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <div class="col s12 m6 offset-m3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Clave {{ cia }}</span>
        <form action="" method="post">
          {% csrf_token %}
          <div class="input-field">
            {{ form.usuario }}
            <label for="id_usuario">Usuario</label>
          </div>
          <div class="input-field">
            {{ form.password }}
            <label for="id_password">Contrasena</label>
          </div>
          <p>
          <input type="submit" class="btn" value="Aceptar"/>
          <a href="{% url 'productor-detail' productor.id %}" class="btn red darken-2">Cancelar</a>
          </p>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block extrajs %}
<script charset="utf-8">
  $(document).ready(function() {
  $('select').formSelect();
  });
</script>
{% endblock %}

seguros/templates/compania/compania_update.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <div class="col s8 m8 offset-m2">
    <div class="card">
      <form action="" method="post"> {% csrf_token %}
        <div class="card-content">
          <span class="card-title">Datos de la compañía</span>
          <div class="input-field">
            {{ form.codigo }}
            <label for="id_codigo">Código</label>
          </div>
          <div class="input-field">
            {{ form.portal_web }}
            <label for="id_portal_web">Portal de productores</label>
          </div>
          <label>
            {{ form.es_descargable }}
            <span>Descargable</span>
          </label>
          <label>
            {{ form.descarga_automatizada }}
            <span>Descarga automatizada</span>
          </label>
          <div class="input-field">
            {{ form.instructivo_descarga }}
            <label for="id_instructivo_descarga">Instructivo Descarga</label>
          </div>
          <div class="input-field">
            {{ form.instructivo_recupero }}
            <label for="id_instructivo_recupero">Instructivo Recupero</label>
          </div>
        </div>
        <div class="card-action center">
          <button type="submit" class="btn">Aceptar</button>
          <a href="{% url 'compania-home' %}" class="btn red darken-2">Cancelar</a>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}
{% block extrajs %}
<script charset="utf-8">
  $(document).ready(function() {
;
})
</script>
{% endblock %}