seguros/productor/urls.py
from django.conf.urls import url
from productor import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='productor-home'),
    url(r'^profile/add/$', views.CreateProfile.as_view(),
        name='productor-create-profile'),
    url(r'^add/$', views.ProductorCreate.as_view(), name='productor-create'),
    url(r'^(?P<pk>\d+)/edit/$', views.ProductorUpdate.as_view(),
        name='productor-update'),
    url(r'^all/$', views.ProductorList.as_view(), name='productor-list'),
    url(r'^search/$', views.productor_search, name='productor-search'),
    url(r'^search/json/$', views.productor_search_to_json,
        name='productor-search-to-json'),
    url(r'^(?P<pk>\d+)/detail/$', views.ProductorDetail.as_view(),
        name='productor-detail'),
    url(r'^localidad/add/$', views.LocalidadCreate.as_view(),
        name='localidad-create'),
    url(r'^provincia/all/$', views.ProvinciaList.as_view(),
        name='provincia-list'),
    url(r'^add-all-provincias/$', views.add_all_provincias,
        name='add-all-provincias'),
    url(r'^licencia/add/$', views.CreateLicencia.as_view(),
        name='create-licencia'),
    url(r'^localidad/(?P<pk>\d+)/detail/$', views.LocalidadDetail.as_view(),
        name='localidad-detail'),
]

seguros/seguros/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from compania import urls as companias_urls
from trabajo import urls as trabajos_urls
# from i18n import urls as i18n_urls
from productor import urls as productores_urls

admin.autodiscover()
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^companias/', include(companias_urls)),
    url(r'^trabajos/', include(trabajos_urls)),
    url(r'^productores/', include(productores_urls)),
    # url(r'^i18n/', include(i18n_urls)),
    url(r'^select2/', include('django_select2.urls')),
]

seguros/productor/models.py
import datetime
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse_lazy

from compania.models import Compania
from trabajo.models import TrabajoDigital, TrabajoImpreso, Trabajo
from productor.variables import (
        OPERACION, COBRANZA, JURIDICA, FISICA, TIPO_PERSONA, SSN_URL,
        PROVINCIAS,
)


def get_provincia_choices():
    choices = [(k, v['nombre']) for k, v in PROVINCIAS.items()]
    return choices


class Licence(models.Model):
    licencia = models.IntegerField()
    licencias_extra = models.IntegerField(blank=True, default=0)
    licencia_preferencial = models.BooleanField(default=False)

    def __str__(self):
        return "Licencia: %s" % self.licence


class Provincia(models.Model):
    codigo = models.IntegerField(choices=get_provincia_choices())

    def __str__(self):
        return self.get_nombre()

    def get_nombre(self):
        try:
            provincia = PROVINCIAS[self.codigo]
            nombre = provincia['nombre']
        except Exception:
            nombre = ''
        return nombre

    def get_nombre_corto(self):
        try:
            provincia = PROVINCIAS[self.codigo]
            nombre_corto = provincia['nombre_corto']
        except Exception:
            nombre_corto = ''
        return nombre_corto

    def get_nombre_abreviado(self):
        try:
            provincia = PROVINCIAS[self.codigo]
            abreviatura = provincia['abreviacion']
        except Exception:
            abreviatura = ''
        return abreviatura

    class Meta:
        ordering = ["codigo"]


class Localidad(models.Model):
    nombre = models.CharField(max_length=100)
    provincia = models.ForeignKey(Provincia, null=True, blank=True)
    descripcion = models.CharField(max_length=240, blank=True)

    def __str__(self):
        return self.nombre

    def get_provincia_name(self):
        provincia = self.provincia
        return provincia.get_nombre()

    def get_absolute_url(self):
        return reverse_lazy('localidad-detail', args=[self.pk, ])

    class Meta:
        verbose_name_plural = "Localidades"
        ordering = ["nombre"]


class Profile(models.Model):
    apellido = models.CharField(max_length=50)
    nombres = models.CharField(max_length=150)
    direccion = models.CharField(max_length=150, blank=True)
    localidad = models.ForeignKey(Localidad, null=True, blank=True)
    telefono = models.CharField(max_length=50, blank=True)
    email = models.EmailField(max_length=50, null=True, blank=True)
    cuit = models.IntegerField(blank=True)

    def __str__(self):
        return self.get_full_name()

    def get_full_name(self):
        return ', '.join((self.apellido.upper(), self.nombres.upper()))

    def get_localidad_name(self):
        localidad = self.localidad
        return localidad.nombre

    def get_provincia_name(self):
        localidad = self.localidad
        return localidad.get_provincia_name()


class Productor(models.Model):
    profile = models.OneToOneField(Profile, on_delete=models.CASCADE)
    licence = models.OneToOneField(Licence, null=True, blank=True)
    tipo_persona = models.IntegerField(default=FISICA, choices=TIPO_PERSONA)
    clave_fiscal = models.CharField(max_length=20, null=True, blank=True)
    matricula = models.IntegerField(unique=True)
    articulo_19 = models.BooleanField(default=False)
    rubrica_digital = models.BooleanField(default=False)
    preferencial = models.BooleanField(default=False)
    trabajo_mensual = models.BooleanField(default=False)

    def __str__(self):
        return self.get_full_name()

    class Meta:
        verbose_name_plural = "Productores"

    def create_digital_work(self, desde, hasta):
        if not self.exist_pending_works():
            work = TrabajoDigital.objects.create(
                    productor=self, fecha_desde=desde, fecha_hasta=hasta)
            work.proponer()

    def get_link_to_ssn(self):
        url = ''
        mat = str(self.matricula)
        if self.tipo_persona == FISICA:
            url = SSN_URL + 'matricula=%s' % mat + "&socpro="
            url += "PAS"
        elif self.tipo_persona == JURIDICA:
            url = SSN_URL + 'socpro=SOC' + "&matricula=%s" % mat
            url += '&apellidorazonsocial=&Submit=Buscar'
        return url

    def get_absolute_url(self):
        return reverse_lazy('productor-detail', args=[str(self.pk), ])

    def get_amount_companies(self):
        res = ProductorEnCompania.objects.filter(productor=self)
        return len(res)

    def get_cuit(self):
        profile = self.profile
        return profile.cuit

    def get_direccion(self):
        profile = self.profile
        return profile.direccion

    def get_localidad_name(self):
        profile = self.profile
        return profile.get_localidad_name()

    def get_provincia_name(self):
        profile = self.profile
        return profile.get_provincia_name()

    def get_full_address(self):
        direccion = self.get_direccion()
        localidad = self.get_localidad_name()
        provincia = self.get_provincia_name()
        full_address = ', '.join([direccion, localidad, provincia])
        return full_address

    def get_full_name(self):
        profile = self.profile
        last_name = profile.apellido
        names = profile.nombres
        full_name = ', '.join([last_name, names])
        return full_name

    def get_email(self):
        profile = self.profile
        return profile.email

    def get_last_active_work(self):
        works = Trabajo.objects.filter(productor=self,
                                       terminado=False).order_by('-fecha')
        return works[0] if works else None

    def get_active_companies(self):
        cias_actives = ProductorEnCompania.objects.filter(
                productor=self, compania__active=True)
        return cias_actives

    def exist_pending_works(self):
        works_digital = TrabajoDigital.objects.filter(productor=self,
                                                      terminado=False)
        works_impreso = TrabajoImpreso.objects.filter(productor=self,
                                                      terminado=False)
        return True if works_digital or works_impreso else False

    def get_active_works(self):
        works = Trabajo.objects.filter(productor=self, terminado=False)
        return works

    def get_productor_en_companias(self):
        pecs = ProductorEnCompania.objects.filter(productor=self)
        return pecs

    def get_active_work(self):
        return Trabajo.objects.get(productor=self, terminado=False)

    def hojas_disponibles(self, tipo):
        pass

    # Las siguientes dos funciones fueron definidas solo para poder usar en el
    # HTML template su valor como "atributo"

    def ultimo_libro_en_uso(self, tipo):
        pass

    def ultimo_libro_en_uso_o(self):
        pass

    def ultimo_libro_en_uso_c(self):
        pass

    def hojas_disponibles_c(self):
        pass

    def hojas_disponibles_o(self):
        pass

    def ultima_hoja(self, tipo):
        pass

    def ultimo_nro_orden(self, tipo):
        pass

    def generacion_hasta(self, tipo):
        pass

    # Carlos Garcia
    def en_stock_actual_anterior(self, tipo, orden_de_impresion):
        pass

    def buscar_libro_actual_y_anterior(self, tipo, orden_de_impresion):
        pass

    def hoja_actual_y_anterior(self, tipo, orden_de_impresion):
        pass

    def orden_actual_y_anterior(self, tipo, orden_de_impresion):
        pass

    def generacion_hasta_link(self, tipo, orden_de_impresion):
        pass

    def fecha_generacion(self, tipo, orden_de_impresion):
        pass

    def impresion_actual_anterior(self, tipo, orden_de_impresion):
        pass

    def companias_vigentes(self, fecha):
        pass

    def cuotas_pendiente(self):
        pass

    def ultimo_cobro(self):
        pass


class Rubrica(models.Model):
    productor = models.ForeignKey(Productor)
    saldo = models.FloatField(default=0.0)

    def get_presupuesto(self):
        return 300

    def get_time_since_the_last_rubrica(self):
        last_book = self.get_last_operacion_book()
        today = datetime.date.today()
        y, m, d = self._get_time_past(last_book.fecha_hasta, today)
        return (y, m, d)

    def _get_time_past(self, before, current):
        days = current.toordinal() - before.toordinal()
        y, days = self._get_amount_years(days)
        m, days = self._get_amount_months(days)
        return y, m, days

    def _get_amount_years(self, days):
        d = days
        y = 0
        while d >= 360:
            y += 1
            d = d - 360
        return y, d

    def _get_amount_months(self, days):
        d = days
        m = 0
        while d >= 30:
            m += 1
            d = d - 30
        return m, d


class RubricaDigital(Rubrica):
    credits = models.IntegerField(default=0)

    def get_last_operacion_book(self):
        books = LibroDigital.objects.filter(rubrica=self, tipo=OPERACION)
        book = books.order_by('-fecha_hasta')[0] if books else None
        return book

    def get_last_cobranza_book(self):
        books = LibroDigital.objects.filter(rubrica=self, tipo=COBRANZA)
        book = books.order_by('-fecha_hasta')[0] if books else None
        return book

    def get_credits_available(self):
        subtotal = self.get_total_records()
        total = self.credits - subtotal
        return total

    def get_total_records(self):
        res = 0
        books = LibroDigital.objects.filter(rubrica=self)
        for book in books:
            res += book.amount_records
        return res


class RubricaImpreso(Rubrica):
    last_sheet = models.IntegerField(default=0)


class Libro(models.Model):
    rubrica = models.ForeignKey(Rubrica)
    fecha_generado = models.DateField(null=True, blank=True)
    fecha_hasta = models.DateField(null=True, blank=True)

seguros/productor/forms.py
from django import forms


class TrabajoImpresoInlineForm(forms.ModelForm):
    pass


class TrabajoDigitalInlineForm(forms.ModelForm):
    pass


class TerminadosInlineForm(forms.ModelForm):
    pass


class NuevaImpresionForm(forms.Form):
    fecha = forms.DateField(required=False, label='Fecha Generacion')
    fechah = forms.DateField(required=False, label='Fecha Hasta')
    libro = forms.CharField(required=False, label='Libro Ope')
    hoja = forms.CharField(required=False, label='Hoja Ope.')
    orden = forms.CharField(required=False, label='Orden Ope.')

    fecha_c = forms.DateField(required=False, label='Fecha Generacion')
    fechah_c = forms.DateField(required=False, label='Fecha Hasta')
    libro_c = forms.CharField(required=False, label='Libro Cob')
    hoja_c = forms.CharField(required=False, label='Hoja Cob.')


class ProductorSearch(forms.Form):
    productor = forms.CharField(required=False, label='Productor',
                                widget=forms.TextInput(attrs={'id': 'search'}))

seguros/productor/views.py
# -*- coding: utf-8 -*-
# pylint: disable-all
import json
from django.shortcuts import render, redirect
from django.http import HttpResponse

from django.views.generic.base import View
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, CreateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from .variables import PROVINCIAS
from . import models


@method_decorator(login_required, 'dispatch')
class CreateProfile(CreateView):
    model = models.Profile
    fields = '__all__'
    template_name = 'productor_create_profile.html'
    success_url = '/productores/'


@method_decorator(login_required, 'dispatch')
class HomeView(TemplateView):
    template_name = 'productor_home.html'


@method_decorator(login_required, 'dispatch')
class ProductorList(ListView):
    model = models.Productor
    template_name = 'productor_list.html'


@method_decorator(login_required, 'dispatch')
class ProductorDetail(DetailView):
    model = models.Productor
    template_name = 'productor_detail.html'


@method_decorator(login_required, 'dispatch')
class ProductorUpdate(UpdateView):
    model = models.Productor
    fields = '__all__'
    template_name = 'productor_update.html'


@method_decorator(login_required, 'dispatch')
class ProductorCreate(CreateView):
    model = models.Productor
    fields = '__all__'
    template_name = 'productor_update.html'


@method_decorator(login_required, 'dispatch')
class ProductorEnCiaList(ListView):
    model = models.ProductorEnCompania
    template_name = 'productor_en_cia_list.html'


@method_decorator(login_required, 'dispatch')
class ProductorEnCiaDetail(DetailView):
    model = models.ProductorEnCompania
    template_name = 'productor_en_cia_detail.html'


@method_decorator(login_required, 'dispatch')
class ProductorEnCiaUpdate(UpdateView):
    model = models.ProductorEnCompania
    fields = '__all__'
    template_name = 'productor_en_cia_update.html'


@method_decorator(login_required, 'dispatch')
class LocalidadCreate(CreateView):
    model = models.Localidad
    fields = '__all__'
    template_name = 'localidad_update.html'


@method_decorator(login_required, 'dispatch')
class ProvinciaList(ListView):
    model = models.Provincia
    template_name = 'provincia_list.html'


@method_decorator(login_required, 'dispatch')
class LocalidadDetail(DetailView):
    model = models.Localidad
    template_name = 'localidad_detail.html'


@method_decorator(login_required, 'dispatch')
class CreateLicencia(CreateView):
    model = models.Licence
    fields = '__all__'
    template_name = 'create_licencia.html'


@login_required
def add_all_provincias(request):
    if request.POST:
        provincia = models.Provincia
        for code, data in PROVINCIAS.items():
            try:
                provincia.objects.get(codigo=code)
            except provincia.DoesNotExist:
                provincia.objects.create(codigo=code)
    return redirect('provincia-list')


def dashboard(request):
    pass


class CrearImpresion(View):
    pass


@login_required
def productor_search_to_json(request):
    q = request.GET.get('q', '')
    profile = models.Profile.objects.filter(nombres__contains=q)
    # Retuturn the value null for materializecss autocomplete
    res = [{'label': p.get_full_name(), 'value': None} for p in profile]
    data = json.dumps(res)
    mimetype = 'application/json'
    return HttpResponse(data, content_type=mimetype)


@login_required
def productor_search(request):
    q = request.GET.get('q', '')
    profiles = models.Profile.objects.filter(nombres__icontains=q)
    return render(request, 'productor_results.html', {'profiles': profiles})

seguros/templates/productor/create_licencia.html
{% extends 'base.html' %}
{% block content %}
<form method="post"> {% csrf_token %}
  <div class='row'>
    <div class='col s12 m6 offset-m3'>
      <div class='card'>
        <div class='card-content'>
          <span class='card-title'>Datos de Licencia</span>
          <div class='row'>
            <div class='input-field col s12'>
              {{ form.licencia }}
              <label for="id_licencia">Licencia</label>
            </div>
          </div>
          <div class='row'>
            <div class='input-field col s12'>
              {{ form.licencias_extra }}
              <label for="id_licencia_extra">Licencia extra</label>
            </div>
          </div>
          <div class='row'>
            <div class='col s12'>
              <label>
                {{ form.licencia_preferencial }}
                <span>Licencia preferencial</span>
              </label>
            </div>
        </div>
        <div class='card-action'>
          <input class="btn" type="submit" value="Aceptar" />
          <button class="btn red darken-3" onclick="window.close()">Cancelar</button> 
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}

seguros/templates/productor/localidad_detail.html
{% extends 'base.html' %}
{% block content %}
<div class='container'>
  <div class='row'>
    <div class='col s12'>
      <div class='card'>
        <div class='card-content'>
          <p>{{ object.nombre }}</p>
          <p>{{ object.provincia }}</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

seguros/templates/productor/localidad_update.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">{% csrf_token %}
  <div class='row'>
    <div class='col s12 m6 offset-m3'>
      <div class='card'>
        <div class='card-content'>
          <span class='card-title'>Información de localidad</span>
          <div class='row'>
            <div class='input-field col s12'>
              {{ form.nombre }}
              <label for="id_nombre">Nombre</label>
            </div>
          </div>
          <div class='row'>
            <div class='input-field col s12'>
              {{ form.provincia }}
              <label for="id_provincia">Provincia</label>
            </div>
          </div>
        </div>
        <div class='card-action center'>
          <input class='btn' type="submit" value="Aceptar" />
          <button class="btn red darken-3" onclick="window.close()">Cancelar</button> 
        </div>
      </div>
    </div>
  </div> 
</form>
{% endblock %}
{% block extrajs %}
<script charset="utf-8">
$(document).ready(function(){
  $('select').formSelect();
});
</script>
{% endblock %}

seguros/templates/productor/nueva_impresion2.html
{% extends "base.html" %}
{% block content %}
<h3>Nueva impresión: {{productor}}</h3>
<div class="row">
  <form action="/productores/trabajo/new/" method="post">
    {% csrf_token %}
    {% if error %}
    <div class="alert alert-danger alert-dismissable">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
      <strong>Alerta!</strong> Debe completar los datos faltante.
    </div>
    {% endif %}
    <div class="row">
    <div class="col m6">
      <div class="card book-row">
        <div class="card-content">
          <span class="card-title">Operaciones</span>
          <div class="input-field">
            <input type="date" name="fecha_op" id="fecha" placeholder="">
            <label for="fecha">Fecha generación</label>
          </div>

          <div class="input-field">
            <input type="date" name="fecha_hasta_op" id="fechah" placeholder="">
            <label for="fechah">Fecha hasta</label>
          </div>
          {% if not productor.libros_digitales %}
          <div class="input-field">
            <input type="number" name="libro_op" id="libro_op">
            <label for="libro_op">Libros Operaciones</label>
          </div>

          <div class="input-field">
            <input type="number" name="hoja_op" id="hoja">
            <label for="hoja">Hoja Operaciones</label>
          </div>

          <div class="input-field">
            <input type="number" name="orden_op" id="orden_op">
            <label for="orden_op">Orden Operaciones</label>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
    <div class="col m6">
      <div class="card book-row">
        <div class="card-content">
          <span class="card-title">Cobranzas</span>
          <div class="input-field">
            <input type="date" name="fecha_co" id="fechac" placeholder="">
            <label for="fechac">Fecha generación</label>
          </div>

          <div class="input-field">
            <input type="date" name="fecha_hasta_co" id="fechahc" placeholder="">
            <label for="fechahc">Fecha hasta</label>
          </div>

          {% if not productor.libros_digitales %}
          <div class="input-field">
            <input type="number" name="libro_co" id="libroc">
            <label for="libroc">Libros Cobranzas</label>
          </div>

          <div class="input-field">
            <input type="number" name="hoja_co" id="hojac">
            <label for="hojac">Hoja Cobranzas</label>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
    </div>
    <div class="row">
      <div class="col m4 offset-m4">
      <button type="Submit" class="btn btn-success">Guardar</button>
      <!--
        <a href="/admin/productores/productor/{{productor.id}}/change/" class="btn btn-danger" role="button">Cancelar</a>
      -->
      <a href="{% url 'productor-detail' productor.id %}" class="btn btn-danger" role="button">Cancelar</a>
      </div>
    </div>
  </form>
</div>
{% endblock%}

seguros/templates/productor/productor_create_profile.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">{% csrf_token %}
  <div class='row'>
    <div class='col s12 m6 offset-m3'>
      <div class='card'>
        <div class='card-content'>
          <span class='card-title'>Información personal</span>
          <div class='row'>
            <div class='input-field col s12'>
              {{ form.apellido }}
              <label for="id_apellido">Apellido</label>
            </div>
          </div>
          <div class='row'>
            <div class='input-field col s12'>
              {{ form.nombres }}
              <label for="id_nombres">Nombres</label>
            </div>
          </div>
          <div class='row'>
            <div class='input-field col s12'>
              {{ form.direccion }}
              <label for="id_direccion">Dirección</label>
            </div>
          </div>
          <div class='row'>
            <div class='input-field col s11'>
              {{ form.localidad }}
              <label for="id_localidad">Localidad</label>
            </div>
            <div class='col s1'>
              <a class='add-popup tooltiped' data-position="bottom" data-tooltip="Crear localidad" target="popup" onclick="window.open('{% url 'localidad-create' %}', 'name', 'width=600,height=650')"><i class='material-icons'>add</i></a>
            </div>
          </div>
          <div class='row'>
            <div class='input-field col s12'>
              {{ form.email }}
              <label for="id_email">Correo electrónico</label>
            </div>
          </div>
          <div class='row'>
            <div class='input-field col s12'>
              {{ form.cuit }}
              <label for="id_cuit">CUIT</label>
            </div>
          </div>
        </div>
        <div class='card-action center'>
          <input class='btn' type="submit" value="Aceptar" />
          <button class="btn red darken-3" onclick="window.close()">Cancelar</button> 
        </div>
      </div>
    </div>
  </div> 
</form>
{% endblock %}
{% block extrajs %}
<script charset="utf-8">
$(document).ready(function(){
  $('select').formSelect();
  $('.tooltiped').tooltip();
});
</script>
{% endblock %}

seguros/templates/productor/productor_export.html
{% extends "suit_base.html" %}
{% block content %}
<h1>Tabla para exportar</h1>
<form action="" method="post">
    {% csrf_token %}
    <button type="submit" class="btn-primary">Exportar a excel</button>
    <table class="table">
        <thead>
            {% for h in cabecera %}
            <th>{{ h }}</th>
            {% endfor %}
        </thead>
        <tbody>
            {% for i in tabla %}
            <tr>
                {% for j in i %}
                <td>{{ j }}</td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</form>
{% endblock %}

seguros/templates/productor/productor_home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container white">
  <h3>Aquí va el dashboard</h3>
</div>
{% endblock %}

seguros/templates/productor/productor_info_update.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <div class="col s12 m6 offset-m3">
    <div class="card">
      <form action="" method="post">
        {% csrf_token %}
        <div class="card-content">
          <span class="card-title">Actualizar informacion</span>
          <div class="input-field">
            {{ form.matricula }}
            <label id="id_matricula">Matricula</label>
          </div>
          <div class="input-field">
            {{ form.cuit }}
            <label for="id_cuit">CUIT</label>
          </div>
          <div class="input-field">
            {{ form.direccion }}
            <label for="id_direccion">Direccion</label>
          </div>
          <div class="input-field">
            {{ form.localidad }}
            <label for="id_localidad">Localidad</label>
          </div>
          <div class="input-field">
            {{ form.provincia }}
            <label for="id_provincia">Provincia</label>
          </div>
          <div class="input-field">
            {{ form.email }}
            <label for="id_email">e-email</label>
          </div>
          <label for="id_libros_digitales">
            {{ form.libros_digitales }}
            <span>Digital</span>
          </label>
        </div>
          <div class="card-action center">
          <input type="submit" class="btn" value="Aceptar"/>
          <a href="{% url 'productor-detail' productor.id %}" class="btn red darken-2">Cancelar</a>
          </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block extrajs %}
<script charset="utf-8">
  $(document).ready(function() {
  $('select').formSelect();
  $('.modal').modal();
  });
</script>
{% endblock %}

seguros/templates/productor/productor_update.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">{% csrf_token %}
  <div class='row'>
    <div class='col s12 m6 offset-m3'>
      <div class='card'>
        <div class='card-content'>
          <span class='card-title'>Nuevo productor</span>
          <div class='row'>
            <div class='input-field col s11'>
              {{ form.profile }}
              <label for="id_profile">Perfil</label>
            </div>
            <a class='col s1 add-popup tooltiped' data-position="bottom" data-tooltip="Crear Perfil" target="popup" onclick="window.open('{% url 'productor-create-profile' %}', 'name', 'width=600,height=650')"><i class='material-icons'>add</i></a>
          </div>
          <div class='row'>
            <div class='input-field col s6'>
              {{ form.matricula }}
              <label for="id_matricula">Matrícula</label>
            </div>
            <div class='input-field col s6'>
              {{ form.clave_fiscal }}
              <label for="id_clave_fiscal">Clave Fiscal</label>
            </div>
          </div>
          <div class='row'>
            <div class='input-field col s4'>
              {{ form.tipo_persona }}
              <label for="id_tipo_persona">Tipo de persona</label>
            </div>
            <div class='input-field col s7'>
              {{ form.licence }}
              <label for="id_licence">Licencia</label>
            </div>
            <a class='col s1 add-popup tooltiped' data-position="bottom" data-tooltip="Crear licencia" target="popup" onclick="window.open('{% url 'create-licencia' %}', 'name', 'width=600,height=650')"><i class='material-icons'>add</i></a>
          </div>
          <div class='row'>
            <div class='col s6'>
              <label>
                {{ form.articulo_19 }}
                <span>Artículo 19</span>
              </label>
            </div>
            <div class='col s6'>
              <label>
                {{ form.rubrica_digital }}
                <span>Rúbrica Digital</span>
              </label>
            </div>
          </div>
          <div class='row'>
            <div class='col s6'>
              <label>
                {{ form.preferencial }}
                <span>Preferencial</span>
              </label>
            </div>
            <div class='col s6'>
              <label>
                {{ form.trabajo_mensual }}
                <span>Trabajo mensual</span>
              </label>
            </div>
          </div> 
        </div>
        <div class='card-action center'>
          <input class='btn' type="submit" value="Aceptar" />
          <button class="btn red darken-3" onclick="window.history.back()">Cancelar</button> 
        </div>
      </div>
    </div>
  </div> 
</form>

{% endblock %}
{% block extrajs %}
<script charset="utf-8">
$(document).ready(function(){
  $('select').formSelect();
  $('.tooltiped').tooltip();
  $("select[required]").css({position: 'absolute', display: 'inline', height: 0, padding: 0, width: 0});
});
</script>
{% endblock %}